# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/axi4_stream_sfp_ethernet_controller.xci
# IP: The module: 'axi4_stream_sfp_ethernet_controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/axi4_stream_sfp_ethernet_controller_gt.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi4_stream_sfp_ethernet_controller_gt || ORIG_REF_NAME==axi4_stream_sfp_ethernet_controller_gt} -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt_ooc.xdc

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi4_stream_sfp_ethernet_controller_gt || ORIG_REF_NAME==axi4_stream_sfp_ethernet_controller_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_exceptions.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/axi4_stream_sfp_ethernet_controller.xci
# IP: The module: 'axi4_stream_sfp_ethernet_controller' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/axi4_stream_sfp_ethernet_controller_gt.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi4_stream_sfp_ethernet_controller_gt || ORIG_REF_NAME==axi4_stream_sfp_ethernet_controller_gt} -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt_ooc.xdc

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==axi4_stream_sfp_ethernet_controller_gt || ORIG_REF_NAME==axi4_stream_sfp_ethernet_controller_gt} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_exceptions.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi4_stream_sfp_ethernet_controller'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
