# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8.xci
# IP: The module: 'fifo_dual_clk_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8.xci
# IP: The module: 'fifo_dual_clk_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_8/fifo_dual_clk_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_dual_clk_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
