# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xci
# IP: The module: 'pll_74_25_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xci
# IP: The module: 'pll_74_25_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_74_25_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
