# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/hudyakovas/Desktop/Khudyakov/MyProjects/RLCBC_BROD/dbg/constraints.xdc

# IP: ip/axi4_stream_sfp_ethernet_controller/axi4_stream_sfp_ethernet_controller.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi4_stream_sfp_ethernet_controller || ORIG_REF_NAME==axi4_stream_sfp_ethernet_controller} -quiet] -quiet
