# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {Labtools 27-2312}  -suppress 
set_msg_config  -id {Labtools 27-3421}  -suppress 
set_msg_config  -id {Labtoolstcl 44-513}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/hudyakovas/Desktop/Khudyakov/MyProjects/Ethernet10G/project/Ethernet10G.runs/synth_1}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/hudyakovas/Desktop/Khudyakov/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/synth_1}}  -suppress 
create_project -in_memory -part xczu9eg-ffvb1156-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/programming/RLCBC_BROD/project/Ethernet10G.cache/wt [current_project]
set_property parent.project_path D:/programming/RLCBC_BROD/project/Ethernet10G.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/programming/RLCBC_BROD/project/Ethernet10G.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/programming/RLCBC_BROD/project/rtl/top.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller_axi_stream_bridge.v
  D:/programming/RLCBC_BROD/project/rtl/status_led_control.v
  D:/programming/RLCBC_BROD/project/rtl/clock_generator.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_reply_transmitter.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_head_reply_builder.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_receiver_lib/ethernet_receiver.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_icmp_checksum_counter.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_receiver_lib/ethernet_header_receiver.v
  D:/programming/RLCBC_BROD/project/rtl/ethernet/ethernet_controller/ethernet_controller.v
  D:/programming/RLCBC_BROD/project/rtl/tb_ethernet_fake_transmitter.v
  D:/programming/RLCBC_BROD/project/rtl/reset_init_block.v
}
read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/axi4_stream_sfp_ethernet_controller.xci
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/ip_0/synth/axi4_stream_sfp_ethernet_controller_gt.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_board.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_exceptions.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/axi4_stream_sfp_ethernet_controller/synth/axi4_stream_sfp_ethernet_controller_ooc.xdc]

read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xci
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload_ooc.xdc]

read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload_keep/fifo_ethernet_payload_keep.xci
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload_keep/fifo_ethernet_payload_keep.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload_keep/fifo_ethernet_payload_keep_ooc.xdc]

read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet.xci
set_property used_in_synthesis false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet_ooc.xdc]

read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xci
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_board.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/pll_74_25_clk/pll_74_25_clk_ooc.xdc]

read_ip -quiet D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_72_72/fifo_72_72.xci
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_72_72/fifo_72_72.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_72_72/fifo_72_72_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_72_72/fifo_72_72_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/programming/RLCBC_BROD/dbg/constraints.xdc
set_property used_in_implementation false [get_files D:/programming/RLCBC_BROD/dbg/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xczu9eg-ffvb1156-3-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
