# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
set_msg_config  -id {Labtools 27-2312}  -suppress 
set_msg_config  -id {Labtools 27-3421}  -suppress 
set_msg_config  -id {Labtoolstcl 44-513}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/hudyakovas/Desktop/Khudyakov/MyProjects/Ethernet10G/project/Ethernet10G.runs/synth_1}}  -suppress 
set_msg_config  -id {Vivado 12-1017}  -string {{WARNING: [Vivado 12-1017] Problems encountered:
1. Failed to delete one or more files in run directory C:/Users/hudyakovas/Desktop/Khudyakov/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/synth_1}}  -suppress 
set_param project.vivado.isBlockSynthRun true
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xczu9eg-ffvb1156-3-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.cache/wt [current_project]
set_property parent.project_path E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64.xci
set_property used_in_implementation false [get_files -all e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64.xdc]
set_property used_in_implementation false [get_files -all e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom  -dir E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1 -new_name fifo_dual_clk_64 -ip [get_ips fifo_dual_clk_64]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top fifo_dual_clk_64 -part xczu9eg-ffvb1156-3-e -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix fifo_dual_clk_64_ fifo_dual_clk_64.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_dual_clk_64_stub.v
 lappend ipCachedFiles fifo_dual_clk_64_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_dual_clk_64_stub.vhdl
 lappend ipCachedFiles fifo_dual_clk_64_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_dual_clk_64_sim_netlist.v
 lappend ipCachedFiles fifo_dual_clk_64_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ fifo_dual_clk_64_sim_netlist.vhdl
 lappend ipCachedFiles fifo_dual_clk_64_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp fifo_dual_clk_64.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips fifo_dual_clk_64]
}

rename_ref -prefix_all fifo_dual_clk_64_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fifo_dual_clk_64.dcp
create_report "fifo_dual_clk_64_synth_1_synth_report_utilization_0" "report_utilization -file fifo_dual_clk_64_utilization_synth.rpt -pb fifo_dual_clk_64_utilization_synth.pb"

if { [catch {
  file copy -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64.dcp e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64.dcp e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64_stub.v e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64_stub.vhdl e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64_sim_netlist.v e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.runs/fifo_dual_clk_64_synth_1/fifo_dual_clk_64_sim_netlist.vhdl e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.ip_user_files/ip/fifo_dual_clk_64]} {
  catch { 
    file copy -force e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.v E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.ip_user_files/ip/fifo_dual_clk_64
  }
}

if {[file isdir E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.ip_user_files/ip/fifo_dual_clk_64]} {
  catch { 
    file copy -force e:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_dual_clk_64/fifo_dual_clk_64_stub.vhdl E:/KhudyakovFiles/MyProjects/RLCBC_BROD/project/Ethernet10G.ip_user_files/ip/fifo_dual_clk_64
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
