# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xci
# IP: The module: 'fifo_ethernet_payload' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ethernet_payload'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ethernet_payload'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xci
# IP: The module: 'fifo_ethernet_payload' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ethernet_payload'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/fifo_ethernet_payload/fifo_ethernet_payload_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ethernet_payload'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
