#set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
#set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

set_property PACKAGE_PIN AK15 [get_ports i_clk_74_25_P]
set_property PACKAGE_PIN AK14 [get_ports i_clk_74_25_N]
set_property IOSTANDARD LVDS_25 [get_ports i_clk_74_25_P]
set_property IOSTANDARD LVDS_25 [get_ports i_clk_74_25_N]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clock_generator_inst/IBUFDS_clk_74_25/O]

# RESET
set_property PACKAGE_PIN AM13 [get_ports i_reset]
set_property IOSTANDARD LVCMOS33 [get_ports i_reset]

# OUTPUT
    # PUSH_BTN
set_property PACKAGE_PIN AG15 [get_ports {i_push_btn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_push_btn[0]}]
set_property PACKAGE_PIN AE14 [get_ports {i_push_btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_push_btn[1]}]
set_property PACKAGE_PIN AF15 [get_ports {i_push_btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_push_btn[2]}]
set_property PACKAGE_PIN AE15 [get_ports {i_push_btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_push_btn[3]}]
set_property PACKAGE_PIN AG13 [get_ports {i_push_btn[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_push_btn[4]}]
    # DIP_sw
set_property PACKAGE_PIN AN14 [get_ports {i_DIP_sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[0]}]
set_property PACKAGE_PIN AP14 [get_ports {i_DIP_sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[1]}]
set_property PACKAGE_PIN AM14 [get_ports {i_DIP_sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[2]}]
set_property PACKAGE_PIN AN13 [get_ports {i_DIP_sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[3]}]
set_property PACKAGE_PIN AN12 [get_ports {i_DIP_sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[4]}]
set_property PACKAGE_PIN AP12 [get_ports {i_DIP_sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[5]}]
set_property PACKAGE_PIN AL13 [get_ports {i_DIP_sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[6]}]
set_property PACKAGE_PIN AK13 [get_ports {i_DIP_sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_DIP_sw[7]}]
    # LED
set_property PACKAGE_PIN AG14 [get_ports {o_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property PACKAGE_PIN AF13 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property PACKAGE_PIN AE13 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {o_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {o_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[4]}]
set_property PACKAGE_PIN AH13 [get_ports {o_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[5]}]
set_property PACKAGE_PIN AH14 [get_ports {o_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[6]}]
set_property PACKAGE_PIN AL12 [get_ports {o_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[7]}]

# ETHERNET 10G
set_property PACKAGE_PIN C8 [get_ports i_clk_156_25_P]
set_property PACKAGE_PIN C7 [get_ports i_clk_156_25_N]
    # Left low (SFP3)
set_property PACKAGE_PIN A4 [get_ports i_ll_rx_p]
set_property PACKAGE_PIN A3 [get_ports i_ll_rx_n]
set_property PACKAGE_PIN A8 [get_ports o_ll_tx_p]
set_property PACKAGE_PIN A7 [get_ports o_ll_tx_n]
set_property PACKAGE_PIN C13 [get_ports o_ll_tx_disable]
set_property IOSTANDARD LVCMOS33 [get_ports o_ll_tx_disable]

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets ila_tx_clk_out]