# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet.xci
# IP: The module: 'ila_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet.xci
# IP: The module: 'ila_ethernet' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/programming/RLCBC_BROD/project/Ethernet10G.srcs/sources_1/ip/ila_ethernet/ila_ethernet_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_ethernet'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
